# Generated by Django 4.1.3 on 2022-12-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='brand_images')),
            ],
        ),
        migrations.CreateModel(
            name='shops_SPB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='shop_images')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='supermarkets_SPB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='shop_images')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='box',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ImageField(upload_to='product_barcodes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='perek_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.brand'),
            preserve_default=False,
        ),
    ]
