# Generated by Django 4.1.3 on 2022-12-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_brand_shops_spb_supermarkets_spb_product_box_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perek_spb',
            old_name='brand',
            new_name='product',
        ),
    ]
