# Generated by Django 4.1.3 on 2022-12-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_brand_perek_spb_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='vkuster_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='vernyi_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='rosneft_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='pyaterechka_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='prisma_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='plovdiv_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='ok_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='magnit_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='lenta_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='dixy_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='briz_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
        migrations.CreateModel(
            name='auchan_spb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField()),
                ('priority', models.IntegerField(unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
        ),
    ]
