# Generated by Django 4.1.3 on 2022-12-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_vkuster_spb_vernyi_spb_rosneft_spb_pyaterechka_spb_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pyaterechka_spb',
            new_name='peterechka_spb',
        ),
    ]
