# Generated by Django 4.1.3 on 2022-12-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_rename_pyaterechka_spb_peterechka_spb'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='brand_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.company'),
            preserve_default=False,
        ),
    ]
