# Generated by Django 4.1.3 on 2022-12-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_company_remove_brand_image_brand_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='company',
            new_name='brand',
        ),
    ]
