# Generated by Django 4.1.3 on 2022-12-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_rename_company_brand_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand',
            new_name='company',
        ),
    ]
