# Generated by Django 4.1.3 on 2022-12-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_brand_somethintelse_alter_brand_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='company',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='somethintelse',
        ),
        migrations.RemoveField(
            model_name='company',
            name='somethintelse',
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
