# Generated by Django 4.1.3 on 2022-12-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_brand_company_alter_company_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peterechka_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.RemoveField(
            model_name='peterechka_spb',
            name='priority',
        ),
        migrations.AddField(
            model_name='peterechka_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
