# Generated by Django 4.1.3 on 2022-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_alter_peterechka_spb_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auchan_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='briz_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='dixy_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='lenta_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='magnit_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='ok_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='perek_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='plovdiv_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='prisma_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='rosneft_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='vernyi_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='vkuster_spb',
            options={'ordering': ['my_order']},
        ),
        migrations.RemoveField(
            model_name='auchan_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='briz_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='dixy_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='lenta_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='magnit_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='ok_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='perek_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='plovdiv_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='prisma_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='rosneft_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='vernyi_spb',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='vkuster_spb',
            name='priority',
        ),
        migrations.AddField(
            model_name='auchan_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='briz_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dixy_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lenta_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='magnit_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ok_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perek_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plovdiv_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prisma_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rosneft_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vernyi_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vkuster_spb',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='shops_spb',
            name='url',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='supermarkets_spb',
            name='url',
            field=models.CharField(max_length=64),
        ),
    ]
