# Generated by Django 4.1.3 on 2022-12-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_alter_auchan_spb_options_alter_briz_spb_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
