# Generated by Django 4.1.3 on 2022-12-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_sity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sity',
            new_name='city',
        ),
    ]
